### ISSUE TITLE
vcf2genotypes does not work

### ISSUE THREAD

**Issue by yocra3** [superyuan/refeditor#1]
Hi,

I am trying your program but I am not able to create the genotypes files, not even in your example. If I run the code that you propose: 

 ./vcf2genotypes test.vcf NA19238 > test.genotypes
./vcf2genotypes: línea 23: get.header: no se encontró la orden
./vcf2genotypes: línea 23: findColumnsContain: no se encontró la orden

no se encontró la orden = Order not found

Can you help me?

Carlos Ruiz

**Comment by superyuan** [comment]
This issue is resolved now.  Please download the up to date version.  Thank you very much for reporting!
